- name: close swap
  shell: "swapoff -a"
  when: not kubelet.swap

- name: close swap onboot
  lineinfile:
    dest: /etc/fstab
    regexp: "(^\\s*[^#].+swap)"
    line: '#\1'
    backrefs: yes
  when: not kubelet.swap

- name: install base package
  yum:
    name:
      - conntrack-tools     # ipvs 模式需要
      - psmisc        # 安装psmisc 才能使用命令killall，它在keepalive的监测脚本中使用到
      - nfs-utils     # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
      - socat               # 用于port forwarding
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - perl           # 内核依赖
      - ipvsadm
      - ipset          # kube-proxy ipvs 模式依赖
      - conntrack
      - libseccomp
      - net-tools
      - sysstat
      - tcpdump
      - lsof
      - wget
    state: latest
    update_cache: yes

- name: send sysctl file
  template:
    src: k8s-sysctl.conf.j2
    dest: /etc/sysctl.d/k8s-sysctl.conf

- name: execute sysctl configuration command
  shell: sysctl -p /etc/sysctl.d/k8s-sysctl.conf
  ignore_errors: true

- name: modules load
  shell: "modprobe {{ item }}"
  with_items:
    - "ip_vs"
    - "ip_vs_rr"
    - "ip_vs_wrr"
    - "ip_vs_sh"
    - "nf_conntrack"
  ignore_errors: true

- name: send modules-load and kubernetes limit config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'k8s-ipvs.conf', dest: "/etc/modules-load.d/" }
    - { src: 'kubernetes.conf', dest: "/etc/security/limits.d/" }

- name: start and enable systemd-modules-load
  systemd:
    name: systemd-modules-load
    state: started
    enabled: yes
