
- name: create kubernetes node directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/pki
    - /etc/kubernetes/manifests
    - /var/log/kubernetes

- name: generate kube-proxy.kubeconfig
  script: kubeconfig.sh {{ KUBE_APISERVER }}
  args:
    executable: bash
  connection: local
  run_once: true

- name: delete kubelet tls files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/kubernetes/pki/kube-proxy*"

- name: install kube-proxy
  block:
    - name: send kube-proxy.kubeconfig and ca files
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - /etc/kubernetes/pki/ca.crt
        - /etc/kubernetes/kube-proxy.kubeconfig

    - name: send kube-proxy binary files
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: u+x
      with_items:
        - /usr/local/bin/kube-proxy

    - name: send kube-proxy config and service files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}"
      with_items:
        - { src: "kube-proxy.service.j2", dest: "/usr/lib/systemd/system" }
        - { src: "kube-proxy.conf.j2", dest: "/etc/kubernetes" }
      notify:
        - restart kube-proxy

- name: start kube-proxy
  systemd:
    name: kube-proxy
    state: started
    enabled: yes
    daemon_reload: yes
