- name: create addons directory
  file:
    path: /etc/kubernetes/addons
    state: directory

- name: config files
  template:
    src: "{{ item }}"
    dest: /etc/kubernetes/addons/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - "kube-proxy.yml.j2"
    - "coredns.yml.j2"
    - "flannel.yml.j2"
    - "metrics-server.yml"
    - "dashboard.yml"

- name: send flannel.yml.j2 and metrics-server.yml files
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/addons/
  with_items:
    - "flannel.yml.j2"
    - "metrics-server.yml"
    - "dashboard.yml"

- name: deploy coredns and metrics-server
  shell: /usr/local/bin/kubectl apply -f /etc/kubernetes/addons/{{ item }}
  with_items:
    - "kube-proxy.yml"
    - "flannel.yml.j2"
    - "coredns.yml"
    - "metrics-server.yml"
    - "dashboard.yml"

